"""add computer tbl

Revision ID: c02147ece3be
Revises: e7b2365acb07
Create Date: 2023-06-08 14:08:33.420191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02147ece3be'
down_revision = 'e7b2365acb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'" users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=' users_pkey'),
    sa.UniqueConstraint('email', name=' users_email_key')
    )
    op.drop_table('computers')
    op.drop_table('users')
    # ### end Alembic commands ###
